---
- name: download and install the zig language toolchain
  become: true
  block:
    - name: remove existing installation
      file:
        path: /usr/local/zig
        state: absent
    - name: fetch zig 0.11 tarball
      get_url:
        url: https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
        dest: /usr/src
      register: tarball
    - name: extract tarball contents to install directory
      unarchive:
        src: "{{ tarball.dest }}"
        dest: /usr/local
